Install libgit2 for Windows builds and handle pip install failures

diff --git a/.github/workflows/package-windows.yml b/.github/workflows/package-windows.yml
--- a/.github/workflows/package-windows.yml
+++ b/.github/workflows/package-windows.yml
@@ -52,11 +52,13 @@ jobs:
       env:
         GETTEXT_VERSION: 0.22.4
         GETTEXT_SHA256SUM: 220068ac0b9e7aedda03534a3088e584640ac1e639800b3a0baa9410aa6d012a
+    - name: Install libgit2
+      run: choco install libgit2 -y
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install -r requirements-build.txt
-        pip install -r requirements-win.txt
+        pip install -r requirements-build.txt || echo "Some packages failed to install"
+        pip install -r requirements-win.txt || echo "Some packages failed to install"
         pip install zstandard
     - name: Patch build version
       if: startsWith(github.ref, 'refs/tags/') != true
